<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Psychowaves</title>
    <?php include("php-include/header.php") ?>

    <div class="eventheader">
        <h1>Terms Of Services</h1>
    </div>
    <div class="maineventheader">
        <div class="privacy-card-contents">

          
            <div class="ng-star-inserted">








                <h4 style="text-align: center" class="ng-star-inserted">Date of last published
                    version: 06 June, 2021</h4>






            </div>
            <br>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>This
                        document is an electronic record in terms of (i) Information Technology Act, 2000; (ii) the
                        rules framed there under as applicable; and (iii) the amended provisions pertaining to
                        electronic records in various statutes as amended by the Information Technology Act, 2000. This
                        electronic record is generated by a computer system and does not require any physical or digital
                        signatures.</span></div>


            </div>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>This
                        document is published in accordance with the provisions of Rule 3 (1) of the Information
                        Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and
                        regulations, privacy policy and Terms for access or usage of www.Psychowaves.com (the
                        <b>"Website"</b>).</span></div>


            </div>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>The Website
                        is owned and operated, run by a PsychoWaves Advance Psychological Services,  registered at 96 South Model Gram,  Ludhiana Punjab</span></div>


            </div>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>These terms
                        of usage <b>("Terms")</b> govern your use of the Website and services provided therein
                        <b>"Services")</b>. By using or visiting the Website, or by using any content or information
                        provided as part of the Website/ Services, you shall be deemed to have read, understood, and
                        accepted to be bound by these Terms. If you do not agree to these Terms, do not use this
                        Website/ Services. Because these Terms are a legal contract between you and Psychowaves, it is
                        important that you review the Terms carefully before accessing or using the Website. These Terms
                        are not intended to alter in any way or limit the terms or conditions of any other agreement
                        that you may have with Psychowaves, including without limitation the privacy policy ("Privacy
                        Policy").</span></div>


            </div>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>For the
                        purpose of these Terms, wherever the context so requires <b>"You"</b>, <b>"Your"</b>,
                        <b>"Customer"</b> or <b>"User"</b> shall mean any natural person who uses the Website for
                        availing the Services. The term <b>"We"</b>, <b>"Us"</b>, <b>"Our"</b>, <b>"Psychowaves"</b> shall
                        mean the Company, its employees, and authorised agents that perform any services on the
                        Company's behalf.</span></div>


            </div>
            <div class="ng-star-inserted">



                <div class="privacy-para ng-star-inserted"><span>We reserve
                        the right to make changes to these Terms at any time. Any such modifications will become
                        effective immediately upon posting to the Website and your continued use of the Website, and/or
                        the Services constitutes your agreement to such modifications. You agree to periodically review
                        the current version of these Terms of Use as posted on the Website.</span></div>


            </div>
            <div class="ng-star-inserted">




                <div class="privacy-para-above-bullet ng-star-inserted"><span>The Website allows Users to connect with
                        counsellors or other individuals
                        <b>("Expert(s)")</b> who provide counselling and therapy services.</span></div>

            </div>
            <div class="ng-star-inserted">





                <ol style="line-height:180%" type="list" class="ng-star-inserted">





                    <li class="privacy-para ng-star-inserted"><b>Use of
                            Services by an incorporated/registered entity</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">If you are not an individual
                                and are an incorporated/registered entity/institute/organisation seeking to avail the
                                services of Psychowaves for your members/employees/students or any individuals registered
                                with you for any services, you shall enter into an agreement/memorandum of understanding
                                with Psychowaves for this purpose. Each individual availing the services of Psychowaves under
                                such agreement/memorandum of understanding shall be bound by these Terms and Privacy
                                Policy available <a href="https://Psychowaves.com/privacyPolicy">here</a>.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Use of
                            Services/Website by minors</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">Use of the Website is
                                available only to persons over the age of eighteen (18). If you are a minor i.e. under
                                the age of eighteen (18) years, you shall not register on the Website without providing
                                us with a duly filled consent form from your legal guardian or parent <b>("Consent
                                    Form")</b>. We reserve the right to terminate your membership and refuse to provide
                                you with access to the Website or Services if it is brought to our notice or if it is
                                discovered that you are under the age of eighteen (18) years and are accessing this
                                Website without furnishing the Consent Form. We will not be liable for any harm caused
                                to you on account of any use of the Website without appropriate parental consent in
                                accordance with this Clause 2.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>User
                            Account</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">In order to use the Website,
                                you may be required to provide information about yourself including your name, email
                                address and other personal information <b>("Personal Information")</b>. You agree that
                                any information you provide to Psychowaves on the Website will always be accurate, correct
                                and up to date. You shall not impersonate someone else or provide account information,
                                an email address or any other information that is not your own. The treatment of your
                                Personal Information and other related information, shall be in accordance with the
                                Privacy Policy.</li>





                            <li class="privacy-para ng-star-inserted">You are responsible for
                                maintaining the confidentiality of your account details at all times. Further, you are
                                responsible for all activities that occur under your account.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Payment</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">We may charge for the chat,
                                audio, and/or video based counselling/face-to-face therapy sessions and other programs.
                                Before availing any such Service, we will communicate in writing to the User, the
                                applicable charges for the said Service. In addition to these Terms, a User shall also
                                be bound by the terms (if any) mentioned for specific Service(s).</li>






                            <li class="privacy-para ng-star-inserted">Please note that the charges
                                paid by a Customer, are not refundable. However, in the event a Customer is not
                                satisfied with the Service provided by Psychowaves, then they may send a mail to
                                info@psychowaves.in. Psychowaves will review each such mail, on a case to case
                                basis, and may refund the charges paid, if it deems fit.


                                <div class="privacy-para-provide-margin-bottom ng-star-inserted">
                                    <span><br>The decision of Psychowaves on any such matter shall be
                                        final and binding.<br><br>Please note the specific refund policy in the event of
                                        the following circumstances:<br></span>
                                </div>
                                <ol style="line-height:180%" type="list">




                                    <li class="privacy-para ng-star-inserted"><b>Care Plan:</b>
                                        &nbsp;&nbsp;Any purchased Care Plan is activated from the date of purchase and
                                        expires according to its duration. In case, the Customer fails to use the
                                        services during the period, the Care Plan cannot be shifted to any other period,
                                        further, no refunds will be provided in such a scenario. The Customer agrees and
                                        understands that buying a Care Plan does not give the Customer any preference
                                        with regard to the allotment of their chat session(s) and/or the Expert of their
                                        choice. All Experts have a pre-defined chat session schedule, which might be
                                        subject to change. The Customer agrees that all requests for chat sessions are
                                        serviced on a first come first serve basis.</li>






                                    <li class="privacy-para ng-star-inserted"><b>Appointments(Audio/Video/Face to
                                            Face):</b>
                                        <ol style="line-height:180%">


                                            <li class="privacy-para ng-star-inserted">For any
                                                Services purchased, the Psychowaves team shall make 3 attempts to reach the
                                                Customer for confirmation of the Services. In case, the Customer fails
                                                to respond within 7 days of the last communication, the Service will be
                                                treated as consumed and no refunds shall be provided by Psychowaves.</li>

                                            <li class="privacy-para ng-star-inserted">In case, of
                                                technical difficulties during or at the time of the session, Psychowaves
                                                will check with their service providers. If the case is adjudged by
                                                Psychowaves to be genuine, the appointment shall be rescheduled. However,
                                                the Customer shall not be entitled to a refund on account of technical
                                                difficulties at the time of the session.</li>

                                            <li class="privacy-para ng-star-inserted">For Audio
                                                and Video Sessions, in case, the Customer fails to turn up at the time
                                                of the appointment, Psychowaves will reschedule the session only once. If
                                                the Customer still does not turn up the second time, the appointment
                                                will be treated as consumed and no refunds shall be provided by
                                                Psychowaves.</li>

                                            <li class="privacy-para ng-star-inserted">For Face to
                                                Face appointments, any no shows are treated as availed services and no
                                                refund or rescheduling shall be provided by Psychowaves in such a scenario.
                                            </li>

                                            <li class="privacy-para ng-star-inserted">For any
                                                reschedules, the Customer needs to inform Psychowaves at least 24 hours in
                                                advance. Unless specifically allowed by the Terms, the Customer shall
                                                not be entitled to a refund for whatever reason.</li>
                                        </ol>
                                    </li>




                                    <li class="privacy-para ng-star-inserted"><b>Appointment
                                            Bundles:</b> &nbsp;&nbsp;All appointment bundles need to be availed within 6
                                        months from the date of purchase. Additionally, all individual items in the
                                        bundles shall also be bound by the terms applicable to appointments.</li>


                                </ol>
                            </li>





                            <li class="privacy-para ng-star-inserted">User(s) can make payments
                                through any of the following available options:

                                <ol style="line-height:180%" type="list">




                                    <li class="privacy-para ng-star-inserted">internet banking;
                                    </li>





                                    <li class="privacy-para ng-star-inserted">debit cards/ credit
                                        Cards;</li>





                                    <li class="privacy-para ng-star-inserted">Unified payments
                                        interface ("UPI");</li>





                                    <li class="privacy-para ng-star-inserted"> Payment wallets
                                        available at the time of payment.</li>


                                </ol>
                            </li>




                            <li class="privacy-para ng-star-inserted">The User agrees and accepts
                                that all nuances and modalities relating to making payment using internet banking/ debit
                                cards/credit cards, UPI or payment wallets <b>("Virtual Payment Mode")</b> shall be
                                separately governed by arrangement(s) / terms and conditions between the User and the
                                relevant banks or payment gateways. We shall not be responsible, in any manner
                                whatsoever, for any liability that may arise in relation to the Virtual Payment Modes
                                (including any fraudulent transaction).</li>





                            <li class="privacy-para ng-star-inserted">While availing any of the
                                Virtual Payment Modes available on the Website, we will not be responsible or assume any
                                liability, whatsoever in respect of any loss or damage arising directly or indirectly to
                                You due to (a) lack of authorization for any transactions; (b) any payment issues
                                arising out of the transaction or (c) decline of such transaction for any reason.</li>





                            <li class="privacy-para ng-star-inserted">You understand, accept and
                                agree that the payment facility provided by us, is neither a banking nor financial
                                service.</li>





                            <li class="privacy-para ng-star-inserted">Psychowaves reserves its right
                                to revise the charges for Services, at any time, without the requirement of any prior
                                intimation to the User. Any such change shall be binding and effective on the User.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Ownership
                            of the Website</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">The Website contains content
                                owned or licensed by Psychowaves <b>("Psychowaves Content")</b>. Psychowaves owns and retains all
                                rights in the Psychowaves Content. You will not remove, alter or conceal any copyright,
                                trademark, service mark or other proprietary rights notices incorporated in or
                                accompanying the Psychowaves Content and you will not reproduce, modify, adapt, prepare
                                derivative works based on, perform, display, publish, distribute, transmit, broadcast,
                                sell, license or otherwise exploit the Psychowaves Content.</li>





                            <li class="privacy-para ng-star-inserted">The Psychowaves name and logo
                                are trademarks of Psychowaves, and may not be copied, imitated or used, in whole or in
                                part, without the prior written permission of Psychowaves. In addition, all custom
                                graphics, button icons and scripts are service marks, trademarks and/or trade dress of
                                Psychowaves, and may not be copied, imitated or used, in whole or in part, without prior
                                written permission from Psychowaves.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Use of the
                            Website and conduct</b>
                        <ol style="line-height:180%" type="list">





                            <li class="privacy-para ng-star-inserted">Use of the Website

                                <ol style="line-height:180%" type="list">




                                    <li class="privacy-para ng-star-inserted">You may use the
                                        Website for lawful purposes only. You shall not post or transmit through the
                                        Website any material which violates or infringes the rights of others, or which
                                        is threatening, abusive, defamatory, libelous, invasive of privacy or publicity
                                        rights, vulgar, obscene, profane or otherwise objectionable, contains injurious
                                        formulas, recipes, or instructions, which encourages conduct that would
                                        constitute a criminal offense, give rise to civil liability or otherwise violate
                                        any applicable law.</li>





                                    <li class="privacy-para ng-star-inserted">You agree not to
                                        engage in any of the following prohibited activities: (i) copying, distributing,
                                        or disclosing any part of the Website in any medium; (ii) transmitting spam,
                                        chain letters, or other unsolicited email by making use of the Services or the
                                        Website; (iv) attempting to interfere with, compromise the system integrity or
                                        security or decipher any transmissions to or from the servers running the
                                        Website; (iii) taking any action that imposes, or may impose in our sole
                                        estimation an unreasonable or disproportionately large load on our
                                        infrastructure; (iv) uploading invalid data, viruses, worms, or other software
                                        agents through the Website; (v) collecting or harvesting any personally
                                        identifiable information, including account names, from the Website; (vi) using
                                        the Website for any commercial purposes without having all necessary rights and
                                        licenses to the User Content (defined below); (vii) impersonating another person
                                        or otherwise misrepresenting your affiliation with a person or entity,
                                        conducting fraud, hiding or attempting to hide your identity; (viii) interfering
                                        with the proper working of the Website; (ix) accessing any content on the
                                        Website through any technology or means other than those capabilities provided
                                        by the Website; or (x) bypassing the measures we may use to prevent or restrict
                                        access to the Website, including without limitation features that prevent or
                                        restrict use or copying of any content or enforce limitations on use of the
                                        Website or the content therein.</li>


                                </ol>
                            </li>





                            <li class="privacy-para ng-star-inserted">User Content Guidelines:

                                <ol style="line-height:180%" type="list">




                                    <li class="privacy-para ng-star-inserted">You are solely
                                        responsible for your conduct and any data that you submit, post or display on or
                                        via the Website. Psychowaves shall have no liability for conduct in relation to
                                        your use of our Website. Violations of these Terms may result in legal
                                        consequences prescribed by the applicable laws.</li>





                                    <li class="privacy-para ng-star-inserted">The Website provides
                                        Users the facility to create, share and post content (together, <b>"User
                                            Content"</b>). Psychowaves claims no ownership rights over User Content created
                                        by you. Psychowaves has the right (but not the obligation) in its sole discretion
                                        to remove any User Content that is stored via the Website.</li>





                                    <li class="privacy-para ng-star-inserted">Psychowaves takes no
                                        responsibility and assumes no liability for any User Content that you or any
                                        other User or third party creates, stores, shares, posts or sends through the
                                        Website. You shall be solely responsible for your User Content and the
                                        consequences of posting, publishing it, or sharing it and you agree that we are
                                        only acting as a passive conduit for your online distribution and publication of
                                        your User Content. If your Content violates these Terms, you may bear legal
                                        responsibility for that content.</li>





                                    <li class="privacy-para ng-star-inserted">You agree not to
                                        post, store, transmit, create or share any User Content that: (i) may create a
                                        risk of harm, loss, physical or mental injury, emotional distress, death,
                                        disability, disfigurement, or physical or mental illness to you, to any other
                                        person, or to any animal; (ii) may create a risk of any other loss or damage to
                                        any person or property; (iii) seeks to harm or exploit children by exposing them
                                        to inappropriate content, asking for personally identifiable details or
                                        otherwise; (iv) may constitute or contribute to a crime or tort under applicable
                                        law; (v) contains any information or content that we deem to be unlawful,
                                        harmful, abusive, racially or ethnically offensive, defamatory, infringing,
                                        invasive of personal privacy or publicity rights, harassing, humiliating to
                                        other people (publicly or otherwise), libelous, threatening, profane, or
                                        otherwise objectionable; (vi) contains any information or content that is
                                        illegal (including, without limitation, the disclosure of insider information
                                        under securities law or of another party's trade secrets); or (vii) contains any
                                        information or content that you do not have a right to make available under
                                        applicable law or under contractual or fiduciary relationships. You agree that
                                        any User Content that you create, store, or share does not and will not violate
                                        third-party rights of any kind, including without limitation any Intellectual
                                        Property Rights (as defined below) or rights of privacy. Psychowaves reserves the
                                        right, but is not obligated, to reject and/or remove any User Content that
                                        Psychowaves believes, in its sole discretion, violates these provisions. For the
                                        purposes of these Terms, "Intellectual Property Rights" means all patent rights,
                                        copyrights, mask work rights, moral rights, rights of publicity, trademark,
                                        trade dress and service mark rights, goodwill, trade secret rights and other
                                        intellectual property rights as may now exist or hereafter come into existence,
                                        and all registered domain names protected under applicable law.</li>






                                    <li class="privacy-para ng-star-inserted"><b>In connection with your User Content,
                                            you affirm,
                                            represent and warrant the following:</b>
                                        <ol style="line-height:180%">


                                            <li class="privacy-para ng-star-inserted">Your User
                                                Content and your use thereof as contemplated by these Terms and the
                                                Website will not violate any applicable law or infringe any rights of
                                                any third party, including but not limited to any Intellectual Property
                                                Rights or privacy rights.</li>

                                            <li class="privacy-para ng-star-inserted">To the
                                                extent that you use the Website for any commercial purpose and your User
                                                Content contains any copyrighted material that is not your original work
                                                or in which you do not otherwise own the copyright, you have obtained
                                                all rights, licenses, consents, and permissions necessary in order to
                                                use that copyrighted material in connection with the creation and/or
                                                dissemination of that User Content using the Website.</li>

                                            <li class="privacy-para ng-star-inserted">Psychowaves may
                                                exercise the rights to your User Content granted under these Terms
                                                without liability for payment of any guild fees, residuals, payments,
                                                fees, or royalties payable under any collective bargaining agreement or
                                                otherwise.</li>

                                            <li class="privacy-para ng-star-inserted">Psychowaves
                                                takes no responsibility and assumes no liability for any User Content
                                                that you or any other User or third party creates, stores, shares,
                                                posts, sends or otherwise makes available through the Website, whether
                                                directly or indirectly. You shall be solely responsible for your User
                                                Content and the consequences of posting, publishing it, or sharing it
                                                and you agree that Psychowaves is only acting a passive conduit for the
                                                distribution and publication of your User Content. If your User Content
                                                violates these Terms, you may have to bear consequences under applicable
                                                law for such User Content.</li>
                                        </ol>
                                    </li>

                                </ol>
                            </li>

                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Rights to
                            User Content</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">If you share your User
                                Content with Psychowaves and/or link your User Content to Psychowaves on a third party service
                                and/or post content on any social media page owned and operated by Psychowaves, you
                                expressly grant and you hereby represent and warrant that you have all rights necessary
                                to grant to Psychowaves a royalty-free, sublicensable, transferable, perpetual,
                                irrevocable, non-exclusive, worldwide license to use, reproduce, modify, publish, list
                                information regarding, edit, translate, distribute, syndicate, publicly perform,
                                publicly display, and make derivative works of all such User Content and your name,
                                voice, and/or likeness as contained in your User Content, in whole or in part, and in
                                any form, media or technology, whether now known or hereafter developed, for use in
                                connection with the Website and Psychowaves's (and its successors' and affiliates')
                                business, including without limitation for promoting and redistributing part or all of
                                our Website (and derivative works thereof) in any media formats and through any media
                                channels.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Disclaimers</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">The advice or information
                                provided by experts via the Website is provided for informational purposes only and
                                cannot be considered a substitute for examination by a doctor or other mental health
                                professional. You are advised strongly against relying solely on, or make decisions
                                based solely on advice provided by any Expert.</li>





                            <li class="privacy-para ng-star-inserted">You understand and agree
                                that although a Expert may be a counsellor, therapist or other mental health
                                professional. Psychowaves disclaims any and all liability for any consultation and therapy
                                services rendered by an Expert to you through the Website. You further acknowledge and
                                agree that you take full responsibility for the decision to access a Expert through the
                                Website and to continue to interact with such individual(s), and that the role of
                                Psychowaves is strictly limited to providing access to such Experts to you.</li>





                            <li class="privacy-para ng-star-inserted">Use of the Services is not
                                for emergencies. If you think you have a medical or mental health emergency, or if at
                                any time you are concerned about your care or treatment, please go to the nearest
                                hospital or health care provider.</li>





                            <li class="privacy-para ng-star-inserted">The Website is not a suicide
                                helpline platform. If you are considering or contemplating suicide or feel that you are
                                a danger to yourself or to others, you may discontinue use of the services immediately
                                at your discretion and please notify appropriate police or emergency medical personnel.
                                If you are thinking about suicide, immediately call a suicide prevention helpline such
                                as Aasra (91-22-27546669).</li>





                            <li class="privacy-para ng-star-inserted">Your use of information
                                provided on the Website and availing of services on the Website is solely at your own
                                risk. Psychowaves is not, and will not in any manner be involved in the practice of
                                medicine or the provision of medical care.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Privacy and
                            security</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">You understand that by using
                                the Website you consent to the collection, use and disclosure of your Personal
                                Information (as defined in the Privacy Policy) and aggregate data as set forth in our
                                Privacy Policy.</li>





                            <li class="privacy-para ng-star-inserted">We endeavor to protect the
                                privacy of your User account and other Personal Information collected by us, but you
                                understand that Psychowaves cannot guarantee that unauthorized third parties will never be
                                able to defeat our security measures or use your personal information for improper
                                purposes. You acknowledge that you provide your Personal Information at your own risk.
                            </li>





                            <li class="privacy-para ng-star-inserted">Your User account is
                                protected by a password for your privacy and security. You need to prevent unauthorized
                                access to your account and Personal Information by ensuring that you keep the login
                                credentials of your User account confidential and limit access to your computer or
                                device and browser by signing off after you have finished accessing your User
                                account.<br><br>To know more about how we protect your Personal Information, read Clause
                                10 of our Privacy Policy.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Warranty</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">The Website is provided on
                                an "as is" basis, and use of the Website is at the User's risk. To the maximum extent
                                permitted by applicable law, the Website is provided without warranties of any kind,
                                whether express or implied, including, but not limited to, implied warranties of
                                merchantability, fitness for a particular purpose, or non-infringement. No advice or
                                information, whether oral or written, obtained by you from Psychowaves or through the
                                Website will not create any warranty not expressly stated herein. Without limiting the
                                foregoing, Psychowaves, its subsidiaries, its affiliates, and its licensors do not warrant
                                that the content found on the website is accurate, reliable or correct; that the Website
                                will meet your requirements; that the Website will be available at any particular time
                                or location, uninterrupted or secure; that any defects or errors will be corrected; or
                                that the Website is free of viruses or other harmful components. Any content downloaded
                                or otherwise obtained through the use of the Website is downloaded at your own risk and
                                you will be solely responsible for any damage to your computer system or mobile device
                                or loss of data that results from such download or your use of the Website.</li>





                            <li class="privacy-para ng-star-inserted">Psychowaves does not warrant,
                                endorse, guarantee, or assume responsibility for any product or service advertised or
                                offered by a third party through the Website or any hyperlinked website or service, and
                                Psychowaves will not be a party to or in any way monitor any transaction between you and
                                third-party providers of products or services.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Excetions
                            and limitations</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">Psychowaves does not make any
                                representation or warranty as to the quality or value of the Services offered on the
                                Website, or availability of Expert(s). Psychowaves does not implicitly or explicitly
                                support or endorse any services on the Website. Psychowaves shall not be liable for any
                                errors or omissions, whether on behalf of itself or third parties.</li>





                            <li class="privacy-para ng-star-inserted">While Psychowaves carries out
                                background checks and verifications on all Experts, you understand and acknowledge that
                                Psychowaves does not endorse, recommend, warrant or guarantee to qualifications, expertise,
                                claims or background of any Expert, or any service, advice, opinion, recommendation
                                provided by an Expert. Nothing contained in these Terms, the Website or on any third
                                party site shall be considered as an endorsement, recommendation, referral,
                                verification, warranty or guarantee with respect to (a) any Expert; (b) the Website or
                                (c) any service, advice, opinion, recommendation made available via the Website or (d)
                                the validity, accuracy, availability, completeness, safety, legality, quality or
                                applicability of any information made available via the Website.</li>





                            <li class="privacy-para ng-star-inserted">You acknowledge that there
                                will be occasions when the Website may be interrupted, including, without limitation,
                                for scheduled maintenance or upgrades, for emergency repairs, or due to failure of
                                telecommunications links and/or equipment.</li>





                            <li class="privacy-para ng-star-inserted">You agree that Psychowaves is
                                not responsible for, and does not endorse User Content posted within the Website.
                                Psychowaves does not have any obligation to prescreen, monitor, edit, or remove any User
                                Content. If your User Content violates these Terms, you shall be solely responsible for
                                all consequences under applicable law with respect to such User Content.</li>





                            <li class="privacy-para ng-star-inserted">Psychowaves reserves the right
                                to remove any User Content from the Website for any reason, without prior notice. User
                                Content removed from the Website may continue to be stored by Psychowaves, including,
                                without limitation, in order to comply with certain legal obligations imposed by
                                applicable law, but may not be retrievable without a valid court order. Psychowaves will
                                not be liable to you for any modification, suspension, or discontinuation of the
                                Website, or the loss of any User Content.</li>





                            <li class="privacy-para ng-star-inserted">We may, without prior
                                notice, change the Website, stop providing the Website or features of the Website, to
                                you or to Users generally, or create usage limits for the Website. We may permanently or
                                temporarily terminate or suspend your access to the Website, or delete any User Content
                                without notice and liability for any reason, including if in our sole determination you
                                violate any provision of these Terms, or for no reason. Upon termination for any reason
                                or no reason, you continue to be bound by these Terms.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Termination</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">Psychowaves may terminate these
                                Terms for any reason at any time. Psychowaves reserves the right, in its sole discretion,
                                to restrict, suspend, or terminate your access to and use of the Website, with or
                                without prior notice. Otherwise applicable sections of the Terms shall survive
                                termination. In addition to any termination rights, we reserve the right to enforce and
                                prosecute any violations of these Terms. You may terminate these Terms at any time by
                                deleting your User account.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Third-party
                            links</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">The Website may contain
                                links to other Websites <b>("Linked Sites")</b>. The Linked Sites are not under the
                                control of the Company. We are not responsible for the content of any Linked Site,
                                including, without limitation to, any link contained in a Linked Site, or any changes or
                                updates to a Linked Site.</li>





                            <li class="privacy-para ng-star-inserted">We are not responsible for
                                any form of transmission, whatsoever, received by the User from any Linked Site. We are
                                providing these links only for convenience, and the inclusion of any such link does not
                                imply endorsement by the Website, of the Linked Sites or any association with its
                                operators or owners including the legal heirs or assigns thereof.</li>





                            <li class="privacy-para ng-star-inserted">On accessing the Linked
                                Sites, you shall be governed by the terms of use, privacy policy and such other
                                additional policies of the Linked Sites. You further acknowledge and agree that we shall
                                not be responsible or liable, directly or indirectly, for any damage or loss caused or
                                alleged to be caused by or in connection with the use of or reliance on any such
                                content, advertising, products, services or other materials available on or through any
                                Linked Sites or for any errors, defamatory content, libel, slander, omissions,
                                falsehoods, obscene content, pornographic material, or any profanity contained therein.
                            </li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Indemnification</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted"> You shall indemnify and
                                hold us harmless from and against any and all losses, damages, settlements, liabilities,
                                costs, charges, assessments and expenses, as well as third party claims and causes of
                                action, including, without limitation, attorneys' fees, arising out of any breach by you
                                of any of these Terms, or any use by you of the Website. You shall provide us with such
                                assistance, without charge, as we may request in connection with any such defence,
                                including, without limitation, providing us with such information, documents, records
                                and reasonable access to you, as we deem necessary. You shall not settle any third party
                                claim or waive any defence without our prior written consent.</li>





                            <li class="privacy-para ng-star-inserted">In the event of a dispute
                                regarding any transaction conducted via the website, you hereby relieve Psychowaves, its
                                affiliates, their respective officers, directors, shareholders, employees,
                                sub-contractors and agents from all manner of actions, claims or demands and from any
                                and all losses (direct, indirect, incidental or consequential), damages, costs or
                                expenses, including, without limitation, court costs and attorneys' fees, which member
                                may have against one or more of the above.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Limitation
                            of liability</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">In no event will Psychowaves or
                                its affiliates or any party involved in creating, producing, or delivering the website
                                be liable for any direct, incidental, consequential, indirect, special, or punitive
                                damages arising out of your access, use, misuse, or inability to use the website or any
                                linked sites, or in connection with any failure of performance. These limitations apply
                                whether the alleged liability is based on contract, tort, negligence, strict liability,
                                or any other basis, even if Psychowaves has been advised of the possibility of such damage.
                            </li>





                            <li class="privacy-para ng-star-inserted">By use of the Website and
                                the Services, the User acknowledges that he/she is solely responsible for any and all
                                actions, liabilities, consequences, decisions, behaviours <b>("Conduct")</b> arising out
                                of or in connection Psychowaves and/or its affiliates responsible for such Conduct.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Dispute
                            Resolution</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">In the event of any dispute,
                                controversy or claim arising out of or relating to this Agreement or any subsequent
                                amendments to this Agreement including, without limitation, the breach of the terms
                                hereunder, termination, validity or invalidity thereof, or any non-contractual issues
                                relating to this Agreement (each, a <b>"Dispute"</b>), each of the Parties will appoint
                                a designated officer to meet for the purpose of endeavouring to resolve such Dispute
                                amicably or to negotiate for an adjustment to such provision.</li>





                            <li class="privacy-para ng-star-inserted">All Disputes, which are not
                                settled pursuant to the issue resolution procedures set forth in Clause 14.1.1 above,
                                will be referred and settled by final and binding arbitration by a sole arbitrator
                                mutually appointed by the Parties in accordance with the Indian Arbitration and
                                Conciliation Act, 1996 as amended from time to time, and the seat of arbitration shall
                                be at Bengaluru.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Governing
                            law</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">This Agreement shall be
                                governed by the laws of India, and subject to Clause 14.2 above, the courts of Bangalore
                                shall have exclusive jurisdiction with respect to any dispute arising hereunder.</li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Grievance
                            officer</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted">In accordance with
                                Information Technology Act, 2000 and rules made there under, the name and contact
                                details of the 'Grievance Officer' are provided below:<br><br><b>Name:</b> Richa
                                Singh<br><br><b>Phone No:</b> 08047097654<br><br><b>E-mail Address:</b>
                                info@psychowaves.in<br><br><b>Postal Address:</b> #2739, 1st Floor, 15th Cross,
                                27th Main Rd, Sector 1, HSR Layout, Bengaluru, Karnataka - 560102
                            </li>


                        </ol>
                    </li>





                    <li class="privacy-para ng-star-inserted"><b>Miscellaneous</b>
                        <ol style="line-height:180%" type="list">




                            <li class="privacy-para ng-star-inserted"><b>Survival:</b> In the
                                event of termination or expiration of these Terms for any reason, any provisions of
                                these Terms that by their nature should survive termination of these Terms will survive
                                termination of these Terms, unless contrary to the pertinent provisions herein stated.
                            </li>





                            <li class="privacy-para ng-star-inserted"><b>Severability:</b> If any
                                term or provision in these Terms is held to be either illegal or unenforceable, in whole
                                or in part, under any enactment or rule of law, such term or provision or part shall to
                                that extent be deemed not to form part of these Terms, but the validity and
                                enforceability of the remainder of these Terms shall not be affected.</li>





                            <li class="privacy-para ng-star-inserted"><b>Unenforceability:</b> If
                                any provision of these Terms or any word, phrase, clause, sentence, or other portion
                                thereof should be held to be unenforceable or invalid for any reason, then provided that
                                the essential consideration for entering into these Terms on the part of any Party is
                                not unreasonably impaired, such provision or portion thereof shall be modified or
                                deleted in such manner as to render these Terms as modified legal and enforceable to the
                                maximum extent permitted under applicable laws.</li>





                            <li class="privacy-para ng-star-inserted"><b>No Waiver:</b> No delay
                                or omission by either Party hereto to exercise any right or power occurring upon any
                                noncompliance or default by the other party with respect to any of the terms of these
                                Terms shall impair any such right or power or be construed to be a waiver thereof. The
                                terms and conditions of these Terms may be waived or amended only in writing or mutual
                                agreement of the Parties. A waiver by either of the Parties hereto of any of the
                                covenants, conditions, or agreements to be performed by the other shall not be construed
                                to be a waiver of any succeeding breach thereof or of any covenant, condition, or
                                agreement herein contained (whether or not the provision is similar).</li>





                            <li class="privacy-para ng-star-inserted"><b>Notices:</b> Any notice
                                required or permitted to be given to Psychowaves hereunder shall be in writing and sent or
                                transmitted by (i) registered or certified mail; (ii) hand-delivery; (iii) email; or
                                (iv) internationally recognized courier service, provided its receipt is acknowledged
                                and, dispatched or sent or transmitted to the address specified Psychowaves. All notice
                                required to be given under these Terms shall be addressed to:<br><br><b>Name:</b>
                                Psychowaves Mental Health<br><br><b>Postal Address:</b> 111, Pritm Nagar, South Model Gram, Ludhiana, Punjab 141002<br><br><b>E-mail Address:</b> info@psychowaves.in</li>


                        </ol>
                    </li>

                </ol>
            </div>
        </div>
    </div>
    <footer>
        <div class="footer">
          <div> 
            <a href=""> <img src="img/icons/facebook .png" alt="" /></a>
            <a href=""> <img src="img/icons/gmail.png" alt="" /></a>
            <a href=""> <img src="img/icons/instagram .png" alt="" /></a>
            <a href=""> <img src="img/icons/twitter.png" alt="" /></a>
            <a href=""> <img src="img/icons/youtube.png" alt="" /></a>
          </div>
          <div class="copyright">
            <p>
              Copyright@2021
              <a href="index.php">PsychoWaves.org</a>
            </p>
            <p><a href="Termsconditions.php">Terms Of Services</a></p>
          </div>
          
        </div>
      </footer>
</body>

</html>